# Generated by Django 5.2.8 on 2025-12-29 14:40

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0003_alter_olxuser_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olxapp',
            name='client_secret',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='olxuser',
            name='access_token',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='olxuser',
            name='refresh_token',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=4096, null=True),
        ),
    ]
