# Generated by Django 6.0.3 on 2026-05-13 15:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0004_encrypt_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlxCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_domain', models.CharField(choices=[('olx.kz', 'olx.kz'), ('olx.bg', 'olx.bg'), ('olx.ro', 'olx.ro'), ('olx.ua', 'olx.ua'), ('olx.pt', 'olx.pt'), ('olx.pl', 'olx.pl')], max_length=10)),
                ('olx_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OlxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_domain', models.CharField(choices=[('olx.kz', 'olx.kz'), ('olx.bg', 'olx.bg'), ('olx.ro', 'olx.ro'), ('olx.ua', 'olx.ua'), ('olx.pt', 'olx.pt'), ('olx.pl', 'olx.pl')], max_length=10)),
                ('olx_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('photos_limit', models.PositiveIntegerField(default=0)),
                ('is_leaf', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='olx.olxcategory')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('client_domain', 'olx_id')},
            },
        ),
        migrations.CreateModel(
            name='OlxDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_domain', models.CharField(choices=[('olx.kz', 'olx.kz'), ('olx.bg', 'olx.bg'), ('olx.ro', 'olx.ro'), ('olx.ua', 'olx.ua'), ('olx.pt', 'olx.pt'), ('olx.pl', 'olx.pl')], max_length=10)),
                ('olx_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='olx.olxcity')),
            ],
            options={
                'ordering': ('city__name', 'name'),
                'unique_together': {('client_domain', 'olx_id')},
            },
        ),
        migrations.CreateModel(
            name='OlxRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_domain', models.CharField(choices=[('olx.kz', 'olx.kz'), ('olx.bg', 'olx.bg'), ('olx.ro', 'olx.ro'), ('olx.ua', 'olx.ua'), ('olx.pt', 'olx.pt'), ('olx.pl', 'olx.pl')], max_length=10)),
                ('olx_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('client_domain', 'olx_id')},
            },
        ),
        migrations.AddField(
            model_name='olxcity',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='olx.olxregion'),
        ),
        migrations.CreateModel(
            name='OlxCategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('values', models.JSONField(blank=True, default=list)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='olx.olxcategory')),
            ],
            options={
                'ordering': ('label',),
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='OlxAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_id', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('pushup_interval_days', models.PositiveIntegerField(default=0)),
                ('pushup_enabled', models.BooleanField(default=False)),
                ('pushup_payment_method', models.CharField(default='account', max_length=20)),
                ('pushup_time', models.TimeField(default=datetime.time(12, 0))),
                ('last_pushup_at', models.DateTimeField(blank=True, null=True)),
                ('next_pushup_at', models.DateTimeField(blank=True, null=True)),
                ('last_pushup_error', models.TextField(blank=True)),
                ('olx_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='olx.olxuser')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverts', to='olx.olxcategory')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverts', to='olx.olxcity')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverts', to='olx.olxdistrict')),
            ],
            options={
                'ordering': ('-id',),
                'unique_together': {('olx_user', 'advert_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='olxcity',
            unique_together={('client_domain', 'olx_id')},
        ),
        migrations.CreateModel(
            name='OlxThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.PositiveBigIntegerField()),
                ('last_message_id', models.PositiveBigIntegerField(default=0)),
                ('olx_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='olx.olxuser')),
            ],
            options={
                'unique_together': {('olx_user', 'thread_id')},
            },
        ),
    ]
