# Generated by Django 6.0.3 on 2026-05-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0005_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='olxthread',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
