# Generated by Django 6.0.3 on 2026-05-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0006_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='olxcity',
            name='county',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='olxcity',
            name='municipality',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
