# Generated by Django 5.2.8 on 2026-01-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('RUB', 'Ruble'), ('KZT', 'Tenge')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='period',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year')], default='day', max_length=10, null=True),
        ),
    ]
