# Generated by Django 5.2.11 on 2026-02-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0003_alter_tariff_currency_alter_tariff_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='self_hosted',
            field=models.BooleanField(default=False),
        ),
    ]
