# Generated by Django 5.2 on 2025-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0002_connectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='code',
            field=models.CharField(default='gulin_35eb6c05-9a48-4ca7-ab75-8b5dfacc31bb', max_length=255, unique=True),
        ),
    ]
