# Generated by Django 5.2.1 on 2025-06-18 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0004_alter_connector_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrix',
            name='member_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appinstance',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='bitrix.bitrix'),
        ),
    ]
