# Generated by Django 5.2.1 on 2025-06-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0007_bitrix_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrix',
            name='domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bitrix',
            name='member_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
