# Generated by Django 5.2.1 on 2025-07-08 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0011_move_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstance',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='appinstance',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='bitrix',
            name='user_id',
        ),
    ]
