# Generated by Django 5.2.1 on 2025-07-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0012_remove_appinstance_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='refresh_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
