# Generated by Django 5.2.4 on 2025-07-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0016_connector_silent'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='asterx',
            field=models.BooleanField(default=False, help_text='Chek for AsterX connector'),
        ),
        migrations.AddField(
            model_name='app',
            name='events',
            field=models.TextField(blank=True, default='ONAPPUNINSTALL'),
        ),
    ]
