# Generated by Django 5.2.5 on 2025-08-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0018_bitrix_imopenlines_auto_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrix',
            name='finish_delay',
            field=models.IntegerField(default=0, help_text='in minutes'),
        ),
    ]
