# Generated by Django 5.2.6 on 2025-09-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0020_app_imopenlines_auto_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='service',
            field=models.CharField(blank=True, choices=[('olx', 'OLX'), ('waweb', 'WhatsApp Web'), ('waba', 'WhatsApp Cloud')], max_length=255, null=True),
        ),
    ]
