# Generated by Django 5.2.5 on 2025-09-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0021_alter_connector_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='silent',
        ),
    ]
