# Generated by Django 5.2.5 on 2025-09-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0022_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='name',
            field=models.CharField(default='openline', max_length=255),
        ),
    ]
