# Generated by Django 5.2.1 on 2025-05-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_navigationsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='tariffpage',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='tariffpage',
            name='og_image',
        ),
    ]
