# Generated by Django 5.2.6 on 2025-09-28 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_articlepage_menu_title_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='footertext',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='footer_text', to='wagtailcore.site'),
            preserve_default=False,
        ),
    ]
