# Generated by Django 5.2.7 on 2025-11-10 06:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_formpage_formfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('code', 3), ('html', 4), ('table', 17)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 2: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 3: ('wagtail.blocks.StructBlock', [[('language', 1), ('code', 2)]], {'label': 'Code'}), 4: ('wagtail.blocks.RawHTMLBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.FloatBlock', (), {'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.URLBlock', (), {'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 11: ('wagtail.blocks.DateTimeBlock', (), {'required': False}), 12: ('wagtail.blocks.DateBlock', (), {'required': False}), 13: ('wagtail.blocks.TimeBlock', (), {'required': False}), 14: ('wagtail.blocks.EmailBlock', (), {'required': False}), 15: ('wagtail.blocks.RawHTMLBlock', (), {'required': False}), 16: ('wagtail.blocks.PageChooserBlock', (), {}), 17: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 5), ('numeric', 6), ('rich_text', 7), ('image', 8), ('url', 9), ('flag', 10), ('datetime', 11), ('date', 12), ('time', 13), ('email', 14), ('html', 15), ('page', 16)]], {})}),
        ),
    ]
