# Generated by Django 5.2.8 on 2025-12-10 15:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('table', 11)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.FloatBlock', (), {'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 6: ('wagtail.blocks.DateTimeBlock', (), {'required': False}), 7: ('wagtail.blocks.DateBlock', (), {'required': False}), 8: ('wagtail.blocks.TimeBlock', (), {'required': False}), 9: ('wagtail.blocks.EmailBlock', (), {'required': False}), 10: ('wagtail.blocks.PageChooserBlock', (), {}), 11: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 1), ('numeric', 2), ('image', 3), ('url', 4), ('flag', 5), ('datetime', 6), ('date', 7), ('time', 8), ('email', 9), ('page', 10)]], {})}),
        ),
    ]
