# Generated by Django 6.0.6 on 2026-07-19 12:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_formpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('code', 3), ('html', 4), ('spoiler', 7), ('gap', 9), ('table', 22)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 2: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 3: ('wagtail.blocks.StructBlock', [[('language', 1), ('code', 2)]], {'label': 'Code'}), 4: ('wagtail.blocks.RawHTMLBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Clickable text to reveal the spoiler.', 'label': 'Spoiler Title'}), 6: ('wagtail.blocks.RichTextBlock', (), {'label': 'Hidden Content'}), 7: ('wagtail.blocks.StructBlock', [[('title', 5), ('content', 6)]], {}), 8: ('wagtail.blocks.IntegerBlock', (), {'default': 32, 'label': 'Height, px', 'max_value': 300, 'min_value': 0}), 9: ('wagtail.blocks.StructBlock', [[('height', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'required': False}), 11: ('wagtail.blocks.FloatBlock', (), {'required': False}), 12: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 14: ('wagtail.blocks.URLBlock', (), {'required': False}), 15: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 16: ('wagtail.blocks.DateTimeBlock', (), {'required': False}), 17: ('wagtail.blocks.DateBlock', (), {'required': False}), 18: ('wagtail.blocks.TimeBlock', (), {'required': False}), 19: ('wagtail.blocks.EmailBlock', (), {'required': False}), 20: ('wagtail.blocks.RawHTMLBlock', (), {'required': False}), 21: ('wagtail.blocks.PageChooserBlock', (), {}), 22: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 10), ('numeric', 11), ('rich_text', 12), ('image', 13), ('url', 14), ('flag', 15), ('datetime', 16), ('date', 17), ('time', 18), ('email', 19), ('html', 20), ('page', 21)]], {})}),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('form', 1), ('gap', 3), ('table', 14)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Form', 'label': 'Form'}), 2: ('wagtail.blocks.IntegerBlock', (), {'default': 32, 'label': 'Height, px', 'max_value': 300, 'min_value': 0}), 3: ('wagtail.blocks.StructBlock', [[('height', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.FloatBlock', (), {'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.URLBlock', (), {'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 9: ('wagtail.blocks.DateTimeBlock', (), {'required': False}), 10: ('wagtail.blocks.DateBlock', (), {'required': False}), 11: ('wagtail.blocks.TimeBlock', (), {'required': False}), 12: ('wagtail.blocks.EmailBlock', (), {'required': False}), 13: ('wagtail.blocks.PageChooserBlock', (), {}), 14: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 4), ('numeric', 5), ('image', 6), ('url', 7), ('flag', 8), ('datetime', 9), ('date', 10), ('time', 11), ('email', 12), ('page', 13)]], {})}),
        ),
    ]
