# Generated by Django 6.0.8 on 2026-10-04 05:07

import django.db.models.deletion
import separator.home.models
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_articlepage_body_alter_formpage_body'),
        ('sites', '0002_alter_site_options_alter_site_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('code', 3), ('html', 4), ('spoiler', 7), ('gap', 9), ('tariffs', 11), ('table', 24)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 2: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 3: ('wagtail.blocks.StructBlock', [[('language', 1), ('code', 2)]], {'label': 'Code'}), 4: ('wagtail.blocks.RawHTMLBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Clickable text to reveal the spoiler.', 'label': 'Spoiler Title'}), 6: ('wagtail.blocks.RichTextBlock', (), {'label': 'Hidden Content'}), 7: ('wagtail.blocks.StructBlock', [[('title', 5), ('content', 6)]], {}), 8: ('wagtail.blocks.IntegerBlock', (), {'default': 32, 'label': 'Height, px', 'max_value': 300, 'min_value': 0}), 9: ('wagtail.blocks.StructBlock', [[('height', 8)]], {}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': separator.home.models.get_service_choices, 'help_text': 'Leave empty to display all services.', 'label': 'Service', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('service', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'required': False}), 13: ('wagtail.blocks.FloatBlock', (), {'required': False}), 14: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 16: ('wagtail.blocks.URLBlock', (), {'required': False}), 17: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 18: ('wagtail.blocks.DateTimeBlock', (), {'required': False}), 19: ('wagtail.blocks.DateBlock', (), {'required': False}), 20: ('wagtail.blocks.TimeBlock', (), {'required': False}), 21: ('wagtail.blocks.EmailBlock', (), {'required': False}), 22: ('wagtail.blocks.RawHTMLBlock', (), {'required': False}), 23: ('wagtail.blocks.PageChooserBlock', (), {}), 24: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 12), ('numeric', 13), ('rich_text', 14), ('image', 15), ('url', 16), ('flag', 17), ('datetime', 18), ('date', 19), ('time', 20), ('email', 21), ('html', 22), ('page', 23)]], {})}),
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trial', models.BooleanField(default=False)),
                ('self_hosted', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('RUB', 'Ruble'), ('KZT', 'Tenge')], max_length=10, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('period', models.CharField(blank=True, choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year')], default='day', max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='home.service')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_tariffs', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_trials', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='home.service')),
            ],
        ),
    ]
