# Generated by Django 6.0.8 on 2026-10-04 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_move_tariff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TariffPage',
        ),
    ]
