# Generated by Django 6.0.8 on 2026-10-04 12:25

import separator.home.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_move_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('code', 3), ('html', 4), ('spoiler', 7), ('gap', 9), ('tariffs', 11), ('subpages', 14), ('table', 27)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 2: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 3: ('wagtail.blocks.StructBlock', [[('language', 1), ('code', 2)]], {'label': 'Code'}), 4: ('wagtail.blocks.RawHTMLBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Clickable text to reveal the spoiler.', 'label': 'Spoiler Title'}), 6: ('wagtail.blocks.RichTextBlock', (), {'label': 'Hidden Content'}), 7: ('wagtail.blocks.StructBlock', [[('title', 5), ('content', 6)]], {}), 8: ('wagtail.blocks.IntegerBlock', (), {'default': 32, 'label': 'Height, px', 'max_value': 300, 'min_value': 0}), 9: ('wagtail.blocks.StructBlock', [[('height', 8)]], {}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': separator.home.models.get_service_choices, 'help_text': 'Leave empty to display all services.', 'label': 'Service', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('service', 10)]], {}), 12: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'If not selected, the current page is used.', 'label': 'Target page', 'required': False}), 13: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Display only first-level pages', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('target_page', 12), ('first_level_only', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'required': False}), 16: ('wagtail.blocks.FloatBlock', (), {'required': False}), 17: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 19: ('wagtail.blocks.URLBlock', (), {'required': False}), 20: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 21: ('wagtail.blocks.DateTimeBlock', (), {'required': False}), 22: ('wagtail.blocks.DateBlock', (), {'required': False}), 23: ('wagtail.blocks.TimeBlock', (), {'required': False}), 24: ('wagtail.blocks.EmailBlock', (), {'required': False}), 25: ('wagtail.blocks.RawHTMLBlock', (), {'required': False}), 26: ('wagtail.blocks.PageChooserBlock', (), {}), 27: ('wagtail.contrib.typed_table_block.blocks.TypedTableBlock', [[('text', 15), ('numeric', 16), ('rich_text', 17), ('image', 18), ('url', 19), ('flag', 20), ('datetime', 21), ('date', 22), ('time', 23), ('email', 24), ('html', 25), ('page', 26)]], {})}),
        ),
    ]
