# Generated by Django 5.2 on 2025-04-21 10:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitrix', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True, verbose_name='Server URL')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('groups_ignore', models.BooleanField(default=True)),
                ('always_online', models.BooleanField(default=False)),
                ('read_messages', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('apikey', models.CharField(blank=True, max_length=255, null=True)),
                ('instanceId', models.CharField(blank=True, max_length=255, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('groups_ignore', models.BooleanField(default=True)),
                ('sms_service', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('app_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wawebs', to='bitrix.appinstance')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wawebs', to='bitrix.line')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
