# Generated by Django 5.2.1 on 2025-05-27 12:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0004_alter_connector_service'),
        ('waweb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaServer',
            new_name='Server',
        ),
        migrations.RenameModel(
            old_name='WaSession',
            new_name='Session',
        ),
    ]
