# Generated by Django 5.2.1 on 2025-05-27 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waweb', '0002_rename_waserver_server_rename_wasession_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='waweb.server'),
        ),
    ]
