# Generated by Django 5.2.7 on 2025-10-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waweb', '0004_server_max_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='sync_history',
            field=models.BooleanField(default=True),
        ),
    ]
