# Generated by Django 5.2.8 on 2025-12-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waweb', '0005_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='url',
            field=models.URLField(help_text='http://127.0.0.1:8080', max_length=255, unique=True, verbose_name='Server URL'),
        ),
    ]
