# Generated by Django 5.2.9 on 2025-12-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waweb', '0006_alter_server_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='url',
            field=models.CharField(help_text='http://127.0.0.1:8080', max_length=255, unique=True, verbose_name='Server URL'),
        ),
    ]
