# Generated by Django 5.2.8 on 2025-12-29 14:40

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waweb', '0007_alter_server_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='api_key',
            field=encrypted_fields.fields.EncryptedCharField(max_length=2000, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='session',
            name='apikey',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=2000, null=True),
        ),
    ]
