# Generated by Django 5.2.4 on 2025-08-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asterx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='vm_send',
            field=models.IntegerField(default=1, help_text='Send VoiceMail to B24: 1 - yes, 0 - no'),
        ),
    ]
