# Generated by Django 5.2.5 on 2025-08-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asterx', '0003_settings_smart_route_alter_settings_crm_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_user_id',
            field=models.IntegerField(default=1, help_text='Default b24 user id for call binding'),
        ),
    ]
