# Generated by Django 5.2.8 on 2026-01-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asterx', '0004_settings_default_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='crm_create',
            field=models.IntegerField(choices=[(0, 'Do not create'), (1, 'Always create'), (2, 'Only for incoming calls'), (3, 'Only for outgoing calls')], default=1, help_text='Rule for creating deals in CRM'),
        ),
    ]
