# Generated by Django 6.0.6 on 2026-09-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asterx', '0005_alter_settings_crm_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='client_first',
            field=models.BooleanField(default=False, help_text='Call first to client, after to operator'),
        ),
        migrations.AddField(
            model_name='settings',
            name='timeout',
            field=models.PositiveBigIntegerField(default=20),
        ),
    ]
