# Generated by Django 6.0.8 on 2026-09-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asterx', '0006_settings_client_first_settings_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='all_statuses',
            field=models.BooleanField(default=False, help_text='Send all failed call statuses to Bitrix'),
        ),
    ]
