CTWA_CONVERSION_EVENTS = [
    "Purchase",
    "LeadSubmitted",
    "InitiateCheckout",
    "AddToCart",
    "ViewContent",
    "OrderCreated",
    "OrderShipped",
    "OrderDelivered",
    "OrderCanceled",
    "OrderReturned",
    "CartAbandoned",
    "QualifiedLead",
    "RatingProvided",
    "ReviewProvided",
]