# Generated by Django 5.2 on 2025-05-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dify',
            name='type',
            field=models.CharField(choices=[('chatflow', 'Chatflow')], default='chatflow', max_length=10),
        ),
    ]
