# Generated by Django 5.2.1 on 2025-06-21 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_integrator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Message',
        ),
    ]
