# Generated by Django 5.2.8 on 2025-12-08 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_site_options_alter_site_domain'),
        ('users', '0008_user_site_alter_user_phone_number_siteprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='sites.site'),
        ),
    ]
