# Generated by Django 6.0.6 on 2026-08-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_site_options_alter_site_domain'),
        ('users', '0009_alter_user_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='message',
            name='site',
        ),
        migrations.AddField(
            model_name='message',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='messages', to='sites.site'),
        ),
    ]
