# Generated by Django 5.2.1 on 2025-05-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwoot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.AlterField(
            model_name='chatwoot',
            name='url',
            field=models.URLField(default='https://app.chatwoot.com/'),
        ),
    ]
