# Generated by Django 5.2.8 on 2025-12-16 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitrix', '0031_app_bitbot'),
        ('sites', '0002_alter_site_options_alter_site_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BitBot', max_length=255)),
                ('bot_id', models.PositiveIntegerField(default=0)),
                ('bot_type', models.CharField(default='O', help_text='B, O or S', max_length=1)),
                ('app_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbots', to='bitrix.appinstance')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.PositiveIntegerField(default=0)),
                ('command', models.CharField(default='help', max_length=255)),
                ('common', models.CharField(default='Y', help_text='Y or N', max_length=1)),
                ('hidden', models.CharField(default='N', help_text='Y or N', max_length=1)),
                ('extranet', models.CharField(default='N', help_text='Y or N', max_length=1)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='bitbot.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=1020, null=True)),
                ('key', models.CharField(max_length=1020)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatbot',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to='bitbot.connector'),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dify_chatflow', 'Dify Chatflow'), ('dify_workflow', 'Dify Workflow')], max_length=255)),
                ('url', models.CharField(max_length=1020)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbotproviders', to='sites.site')),
            ],
        ),
        migrations.AddField(
            model_name='connector',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connectors', to='bitbot.provider'),
        ),
        migrations.CreateModel(
            name='CommandLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='ru', help_text='en, ru, de..', max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('params', models.CharField(blank=True, max_length=500, null=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='bitbot.command')),
            ],
            options={
                'unique_together': {('command', 'language')},
            },
        ),
    ]
