# Generated by Django 5.2.8 on 2025-12-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='name',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('typebot', 'Typebot'), ('dify_chatflow', 'Dify Chatflow'), ('dify_workflow', 'Dify Workflow')], max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='url',
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
    ]
