# Generated by Django 5.2.8 on 2025-12-29 14:40

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitbot', '0002_typebot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='key',
            field=encrypted_fields.fields.EncryptedCharField(max_length=2000),
        ),
    ]
