# Generated by Django 6.0.2 on 2026-03-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbot', '0003_encrypt_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='batch_delay',
            field=models.PositiveIntegerField(default=10, help_text='Delay in seconds before sending accumulated messages. 0 disables batching.', verbose_name='Batch delay'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('typebot', 'Typebot'), ('dify_chatflow', 'Dify Chatflow'), ('dify_workflow', 'Dify Workflow'), ('custom', 'Custom API')], max_length=255),
        ),
    ]
