# Generated by Django 6.0.6 on 2026-06-20 13:52

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbot', '0004_upd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='batch_delay',
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='bot_type',
            field=models.CharField(default='openline', help_text='bot, openline or supervisor', max_length=20),
        ),
        migrations.AlterField(
            model_name='connector',
            name='key',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=2000, null=True),
        ),
    ]
