# Generated by Django 5.2.4 on 2025-07-28 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitrix', '0017_app_asterx_app_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My PBX', max_length=255)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('setup_complete', models.BooleanField(default=False)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pbx_uuid', models.UUIDField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='from-internal', max_length=255)),
                ('endpoint', models.CharField(default='100', max_length=255)),
                ('type', models.CharField(choices=[('exclude', 'Exclude'), ('external', 'External'), ('internal', 'Internal')], default='exclude', max_length=10)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asterx.server')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_card', models.IntegerField(default=2, help_text='0 - not show, 1 - on call, 2 - on answer')),
                ('crm_create', models.IntegerField(default=1, help_text='1 - yes, 0 - no')),
                ('app_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asterx_settings', to='bitrix.appinstance')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='asterx.settings'),
        ),
    ]
