# Generated by Django 5.2.4 on 2025-08-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asterx', '0002_settings_vm_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='smart_route',
            field=models.BooleanField(default=False, help_text='Find a manager in Bitrix and connect with him'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='crm_create',
            field=models.BooleanField(default=True, help_text='Create Deal on B24'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='vm_send',
            field=models.BooleanField(default=True, help_text='Send VoiceMail to B24'),
        ),
    ]
