# Generated by Django 5.2.1 on 2025-06-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='integrator',
            field=models.BooleanField(default=False),
        ),
    ]
