# Generated by Django 5.2.5 on 2025-08-20 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='voip.gulin.kz', max_length=255)),
                ('sip_port', models.PositiveIntegerField(default=5061)),
                ('ext_digits', models.PositiveIntegerField(default=5)),
                ('client_id', models.CharField(max_length=500, unique=True)),
                ('client_secret', models.CharField(max_length=500)),
                ('gql_scopes', models.CharField(default='gql:framework gql:core', max_length=500, verbose_name='Allowed Scopes')),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('password', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sip_extensions', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extensions', to='freepbx.server')),
            ],
        ),
    ]
