# Generated by Django 5.2.8 on 2025-12-29 14:40

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freepbx', '0002_extension_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='password',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='client_id',
            field=encrypted_fields.fields.EncryptedCharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='client_secret',
            field=encrypted_fields.fields.EncryptedCharField(max_length=500),
        ),
    ]
