# Generated by Django 5.2 on 2025-04-21 10:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitrix', '__first__'),
        ('chatwoot', '__first__'),
        ('sites', '0002_alter_site_options_alter_site_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, unique=True)),
                ('config_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('access_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('api_version', models.IntegerField(default=20)),
                ('verify_token', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waba_apps', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='Waba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waba_id', models.CharField(max_length=255, unique=True)),
                ('access_token', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lang', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('waba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='waba.waba')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone_id', models.CharField(max_length=50, unique=True)),
                ('sms_service', models.BooleanField(default=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('app_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='bitrix.appinstance')),
                ('inbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatwoot.inbox')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='bitrix.line')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('waba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='waba.waba')),
            ],
        ),
    ]
