# Generated by Django 5.2.4 on 2025-08-17 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='calling',
            field=models.CharField(blank=True, choices=[('enabled', 'ENABLED'), ('disabled', 'DISABLED')], default='disabled', max_length=10),
        ),
        migrations.AddField(
            model_name='phone',
            name='error',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='sip_hostname',
            field=models.CharField(blank=True, default='pbx.gulin.kz', max_length=200),
        ),
        migrations.AddField(
            model_name='phone',
            name='sip_port',
            field=models.PositiveIntegerField(blank=True, default=5061),
        ),
        migrations.AddField(
            model_name='phone',
            name='sip_status',
            field=models.CharField(blank=True, choices=[('enabled', 'ENABLED'), ('disabled', 'DISABLED')], default='enabled', max_length=10),
        ),
        migrations.AddField(
            model_name='phone',
            name='srtp_key_exchange_protocol',
            field=models.CharField(blank=True, choices=[('DTLS', 'DTLS'), ('SDES', 'SDES')], default='SDES', max_length=10),
        ),
        migrations.AlterField(
            model_name='app',
            name='access_token',
            field=models.CharField(blank=True, help_text='System admin user access_token', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='waba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='waba.waba'),
        ),
        migrations.AlterField(
            model_name='template',
            name='waba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='waba.waba'),
        ),
    ]
