# Generated by Django 5.2.5 on 2025-08-20 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freepbx', '0001_initial'),
        ('waba', '0002_calling'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='sip_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freepbx.server'),
        ),
        migrations.AddField(
            model_name='phone',
            name='call_dest',
            field=models.CharField(blank=True, choices=[('disabled', 'Disabled'), ('b24', 'Bitrix24'), ('ext', 'SIP Extension'), ('pbx', 'SIP Server')], default='disabled', max_length=10),
        ),
        migrations.AddField(
            model_name='phone',
            name='sip_extensions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freepbx.extension'),
        ),
        migrations.AddField(
            model_name='phone',
            name='voximplant_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='sip_hostname',
            field=models.CharField(blank=True, default='voip.gulin.kz', max_length=200),
        ),
    ]
