# Generated by Django 5.2 on 2025-04-21 10:08

import django.db.models.deletion
import thoth.bot.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitrix', '0001_initial'),
        ('chatwoot', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='text', max_length=25)),
                ('max_completion_tokens', models.PositiveIntegerField(default=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocal', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1500)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='bot.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_human', models.TextField()),
                ('description_openai', models.JSONField()),
                ('type', models.CharField(choices=[('instruction', 'instruction'), ('function', 'function')], max_length=50)),
                ('engine', models.CharField(choices=[('text', 'text'), ('voice', 'voice')], default='text', max_length=50)),
                ('privacy', models.CharField(choices=[('private', 'private'), ('public', 'public')], max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up', models.CharField(default='follow_up', max_length=255)),
                ('assistant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('vector_store', models.CharField(blank=True, max_length=255, null=True)),
                ('system_message', models.TextField()),
                ('speech_to_text', models.BooleanField(default=True)),
                ('stt_model', models.CharField(default='whisper-1', max_length=255)),
                ('memory_days', models.PositiveIntegerField(default=2)),
                ('memory_count', models.PositiveIntegerField(default=15)),
                ('temperature', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('max_completion_tokens', models.PositiveIntegerField(default=4096)),
                ('top_p', models.DecimalField(decimal_places=2, default=0.9, max_digits=3)),
                ('frequency_penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('presence_penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('agent_bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='chatwoot.agentbot')),
                ('bitrix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='bitrix.appinstance')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='bot.apikey')),
                ('features', models.ManyToManyField(blank=True, related_name='bots', to='bot.feature')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='bot.model')),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='bot.provider'),
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.CharField(default=thoth.bot.models.generate_uuid, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('instruction', models.TextField()),
                ('welcome_msg', models.TextField(blank=True, null=True)),
                ('transfer_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('max_tokens', models.PositiveIntegerField(default=4096)),
                ('features', models.ManyToManyField(blank=True, related_name='voices', to='bot.feature')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voices', to='bot.model')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voices', to='bot.apikey')),
                ('vocal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voices', to='bot.vocal')),
            ],
        ),
    ]
