# Generated by Django 5.2 on 2025-05-06 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        ('dify', '0003_alter_dify_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='dify_workflow',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'workflow'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voices', to='dify.dify'),
        ),
    ]
