# Generated by Django 5.2.1 on 2025-06-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waweb', '0003_session_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='max_connections',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
