# Generated by Django 5.2 on 2025-04-30 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatwoot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('chatflow', 'Chatflow'), ('workflow', 'Workflow')], max_length=10)),
                ('base_url', models.URLField(default='https://api.dify.ai/v1')),
                ('api_key', models.CharField(max_length=255)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('agent_bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dify', to='chatwoot.agentbot')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dify', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
