#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

QUEUE="${CELERY_QUEUE:-celery}"
CONCURRENCY="${CELERY_CONCURRENCY:-3}"
MAX_TASKS_PER_CHILD="${CELERY_MAX_TASKS_PER_CHILD:-1000}"
MAX_MEMORY_PER_CHILD="${CELERY_MAX_MEMORY_PER_CHILD:-400000}" # 400MB

if [ "$CONCURRENCY" -eq 0 ]; then
    echo "Worker for queue $QUEUE is disabled (concurrency set to 0)."
    tail -f /dev/null
fi

echo "Starting Celery worker for queue: $QUEUE with concurrency: $CONCURRENCY"

celery -A config.celery_app worker \
    -l info \
    -c "$CONCURRENCY" \
    -Q "$QUEUE" \
    --max-tasks-per-child="$MAX_TASKS_PER_CHILD" \
    --max-memory-per-child="$MAX_MEMORY_PER_CHILD"
