# Generated by Django 5.2 on 2025-04-30 07:39

import separator.bitrix.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0002_connectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='code',
            field=models.CharField(default=separator.bitrix.models.generate_uuid, max_length=255, unique=True),
        ),
    ]
