# Generated by Django 5.2 on 2025-05-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0003_alter_connector_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='service',
            field=models.CharField(blank=True, choices=[('olx', 'OLX'), ('waweb', 'WhatsApp Web'), ('waba', 'WhatsApp API')], max_length=255, null=True),
        ),
    ]
