# Generated by Django 5.2.1 on 2025-06-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0005_bitrix_member_id_alter_appinstance_portal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitrix',
            name='client_endpoint',
        ),
    ]
