# Generated by Django 5.2.1 on 2025-06-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0006_remove_bitrix_client_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrix',
            name='protocol',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='https', max_length=5),
        ),
    ]
