# Generated by Django 5.2.1 on 2025-07-10 12:49

import separator.bitrix.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0013_credential_refresh_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='connector_icons/', validators=[separator.bitrix.models.validate_svg]),
        ),
    ]
