# Generated by Django 5.2.1 on 2025-07-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0014_alter_connector_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='autologin',
            field=models.BooleanField(default=True),
        ),
    ]
