# Generated by Django 5.2.1 on 2025-07-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0015_app_autologin'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='silent',
            field=models.CharField(default='Y', help_text='im.disk.file.commit SILENT_MODE (Y/N)', max_length=1),
        ),
    ]
