# Generated by Django 5.2.5 on 2025-08-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0017_app_asterx_app_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrix',
            name='imopenlines_auto_finish',
            field=models.BooleanField(default=False),
        ),
    ]
