# Generated by Django 5.2.5 on 2025-08-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0019_bitrix_finish_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='imopenlines_auto_finish',
            field=models.BooleanField(default=False, help_text='Enable auto finish chat'),
        ),
    ]
