# Generated by Django 5.2.5 on 2025-09-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0023_line_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstance',
            name='exclude',
            field=models.CharField(blank=True),
        ),
    ]
