# Generated by Django 5.2.7 on 2025-10-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0024_appinstance_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='name',
            field=models.CharField(default='separator.biz', max_length=255),
        ),
    ]
