# Generated by Django 5.2.7 on 2025-10-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0025_alter_connector_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='vendor',
            field=models.BooleanField(default=False, help_text='Chek for Separator partner App'),
        ),
    ]
