# Generated by Django 5.2.7 on 2025-10-18 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0026_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmessage',
            name='app_users',
        ),
        migrations.RemoveField(
            model_name='appinstance',
            name='attempts',
        ),
        migrations.AddField(
            model_name='adminmessage',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='bitrix.app'),
        ),
    ]
