# Generated by Django 5.2.7 on 2025-10-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0027_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstance',
            name='fileAsUrl',
            field=models.BooleanField(default=False, help_text='Send file as URL, not base64'),
        ),
    ]
