# Generated by Django 5.2.7 on 2025-10-21 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0028_appinstance_fileasurl'),
        ('waba', '0006_alter_template_content'),
        ('waweb', '0005_vendor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminMessage',
            new_name='ImNotify',
        ),
        migrations.CreateModel(
            name='Messageservice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='SMS', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageservice', to='bitrix.bitrix')),
                ('wa_cloud', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messageservice', to='waba.phone')),
                ('wa_web', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messageservice', to='waweb.session')),
            ],
        ),
    ]
