# Generated by Django 5.2.8 on 2025-12-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0029_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messageservice',
        ),
    ]
