# Generated by Django 5.2.8 on 2025-12-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0030_delete_messageservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='bitbot',
            field=models.BooleanField(default=False, help_text='Chek for BitBot App'),
        ),
    ]
