# Generated by Django 5.2.8 on 2025-12-29 14:40

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0031_app_bitbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='client_secret',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='credential',
            name='access_token',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='credential',
            name='refresh_token',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=2000),
        ),
    ]
