# Generated by Django 5.2.11 on 2026-02-22 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0032_encrypt_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plasement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('placement', models.TextField(blank=True, null=True)),
                ('handler', models.CharField(default='/placement/', max_length=2500)),
                ('useBuiltInInterface', models.BooleanField(default=False)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='bitrix.app')),
            ],
        ),
    ]
