# Generated by Django 5.2.11 on 2026-02-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0033_plasement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='imopenlines_auto_finish',
        ),
        migrations.RemoveField(
            model_name='bitrix',
            name='finish_delay',
        ),
        migrations.RemoveField(
            model_name='bitrix',
            name='imopenlines_auto_finish',
        ),
        migrations.AddField(
            model_name='app',
            name='min_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appinstance',
            name='license',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
