# Generated by Django 5.2.10 on 2026-03-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0034_upd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstance',
            name='license',
        ),
        migrations.AddField(
            model_name='bitrix',
            name='license',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
