# Generated by Django 5.2.11 on 2026-03-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0035_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='default_line_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
