# Generated by Django 6.0.2 on 2026-03-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0036_connector_default_line_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstance',
            name='ctwa',
            field=models.BooleanField(default=False, help_text='Check for CTWA tracking'),
        ),
    ]
