# Generated by Django 6.0.2 on 2026-03-12 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0037_appinstance_ctwa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('method', models.CharField(max_length=512)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('app_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apicalls', to='bitrix.appinstance')),
            ],
        ),
    ]
