# Generated by Django 6.0.2 on 2026-03-15 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0038_apicall'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='save_events',
            field=models.BooleanField(default=False, help_text='Chek for save inbound events'),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_records', to='bitrix.app')),
                ('portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bitrix.bitrix')),
            ],
        ),
    ]
