# Generated by Django 6.0.5 on 2026-05-19 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0039_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstance',
            name='ctwa',
        ),
        migrations.AddField(
            model_name='apicall',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apicalls', to='bitrix.app'),
        ),
        migrations.AddField(
            model_name='app',
            name='handler',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=1000)),
                ('method', models.CharField(max_length=512)),
                ('placements', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, null=True)),
                ('active', models.BooleanField(default=True)),
                ('apps', models.ManyToManyField(blank=True, related_name='features', to='bitrix.app')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='bitrix.feature')),
                ('portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_grants', to='bitrix.bitrix')),
            ],
        ),
        migrations.DeleteModel(
            name='Plasement',
        ),
        migrations.AddConstraint(
            model_name='featuregrant',
            constraint=models.UniqueConstraint(fields=('portal', 'code'), name='bitrix_featuregrant_portal_code_unique'),
        ),
    ]
