# Generated by Django 6.0.5 on 2026-05-20 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0040_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='app_instance',
        ),
        migrations.RemoveField(
            model_name='line',
            name='owner',
        ),
        migrations.AlterField(
            model_name='line',
            name='connector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='bitrix.connector'),
        ),
    ]
