# Generated by Django 6.0.3 on 2026-05-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0041_line_upd'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='featuregrant',
            name='bitrix_featuregrant_portal_code_unique',
        ),
        migrations.AddField(
            model_name='feature',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='featuregrant',
            constraint=models.UniqueConstraint(fields=('portal', 'feature'), name='bitrix_featuregrant_portal_feature_unique'),
        ),
        migrations.RemoveField(
            model_name='featuregrant',
            name='code',
        ),
    ]
