# Generated by Django 6.0.5 on 2026-06-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0042_feature_upd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinstance',
            name='fileAsUrl',
            field=models.BooleanField(default=True, help_text='Send file as URL, not base64'),
        ),
    ]
