# Generated by Django 6.0.5 on 2026-06-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0043_alter_appinstance_fileasurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='handler',
            field=models.CharField(blank=True, help_text='Base URL', max_length=1000),
        ),
    ]
