# Generated by Django 6.0.8 on 2026-10-03 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0044_alter_app_handler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstance',
            name='exclude',
        ),
    ]
