# Generated by Django 5.2.5 on 2025-08-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freepbx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
