# Generated by Django 5.2.5 on 2025-08-31 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0003_sip'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='callback_permission_status',
            field=models.CharField(blank=True, choices=[('enabled', 'ENABLED'), ('disabled', 'DISABLED')], default='enabled', max_length=10),
        ),
        migrations.AddField(
            model_name='phone',
            name='sip_user_password',
            field=models.CharField(blank=True, help_text='Whatsapp Cloud SIP Password', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='waba',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waba.app'),
        ),
    ]
