# Generated by Django 5.2.6 on 2025-10-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0004_sip'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='pin',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
