# Generated by Django 5.2.7 on 2025-10-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0005_phone_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
