# Generated by Django 5.2.7 on 2025-11-05 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_site_options_alter_site_domain'),
        ('waba', '0006_alter_template_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='events',
            field=models.BooleanField(default=False, help_text='Chek for save inbound events'),
        ),
        migrations.AlterField(
            model_name='app',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='waba_apps', to='sites.site'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('waba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='waba.waba')),
            ],
        ),
    ]
