# Generated by Django 5.2.7 on 2025-11-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0007_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('details', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
