# Generated by Django 5.2.7 on 2025-11-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0008_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('cloud', 'cloud'), ('app', 'app')], default='cloud', max_length=10),
        ),
    ]
