# Generated by Django 5.2.8 on 2025-12-29 14:40

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0009_phone_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='access_token',
            field=encrypted_fields.fields.EncryptedCharField(default='', help_text='System admin user access_token', max_length=2000),
        ),
        migrations.AlterField(
            model_name='app',
            name='client_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='app',
            name='client_secret',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='app',
            name='config_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='waba',
            name='access_token',
            field=encrypted_fields.fields.EncryptedCharField(max_length=2000),
        ),
    ]
