# Generated by Django 5.2.8 on 2026-01-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0010_encrypt_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='original',
            field=models.BooleanField(default=True),
        ),
    ]
