# Generated by Django 5.2.10 on 2026-02-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0011_error_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='waba',
            name='subscribed',
            field=models.BooleanField(default=True, help_text='Subscribed to webhook events'),
        ),
    ]
