# Generated by Django 5.2.11 on 2026-02-27 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0012_waba_subscribed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='availableInB24',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='TemplateBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('delivered', 'delivered'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='waba.phone')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='waba.template')),
            ],
            options={
                'verbose_name': 'Broadcast',
                'verbose_name_plural': 'Broadcasts',
            },
        ),
        migrations.CreateModel(
            name='TemplateBroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20)),
                ('wamid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('delivered', 'delivered'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('error_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='waba.templatebroadcast')),
            ],
            options={
                'verbose_name': 'Recipient',
                'verbose_name_plural': 'Recipients',
            },
        ),
        migrations.CreateModel(
            name='TemplateComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HEADER', 'HEADER'), ('BODY', 'BODY'), ('FOOTER', 'FOOTER'), ('BUTTONS', 'BUTTONS')], max_length=20)),
                ('format', models.CharField(blank=True, choices=[('TEXT', 'TEXT'), ('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('GIF', 'GIF'), ('DOCUMENT', 'DOCUMENT'), ('LOCATION', 'LOCATION')], max_length=20, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='waba.template')),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
            },
        ),
        migrations.CreateModel(
            name='TemplateComponentButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QUICK_REPLY', 'QUICK_REPLY'), ('URL', 'URL'), ('PHONE_NUMBER', 'PHONE_NUMBER'), ('VOICE_CALL', 'VOICE_CALL'), ('COPY_CODE', 'COPY_CODE'), ('MPM', 'MPM'), ('SPM', 'SPM'), ('OTP', 'OTP')], max_length=20)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='waba.templatecomponent')),
            ],
            options={
                'verbose_name': 'Button',
                'verbose_name_plural': 'Buttons',
            },
        ),
        migrations.CreateModel(
            name='TemplateComponentNamedParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('example', models.TextField(blank=True, null=True)),
                ('button', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='named_params', to='waba.templatecomponentbutton')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='named_params', to='waba.templatecomponent')),
            ],
            options={
                'verbose_name': 'NamedParam',
                'verbose_name_plural': 'NamedParams',
            },
        ),
        migrations.CreateModel(
            name='TemplateComponentPositionalParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('example', models.TextField(blank=True, null=True)),
                ('button', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positional_params', to='waba.templatecomponentbutton')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positional_params', to='waba.templatecomponent')),
            ],
            options={
                'verbose_name': 'PosParam',
                'verbose_name_plural': 'PosParams',
            },
        ),
    ]
