# Generated by Django 5.2.11 on 2026-03-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0013_template_upd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatebroadcast',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('delivered', 'delivered'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='templatebroadcastrecipient',
            name='recipient_phone',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='templatebroadcastrecipient',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('delivered', 'delivered'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='templatecomponent',
            name='format',
            field=models.CharField(blank=True, choices=[('TEXT', 'TEXT'), ('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('GIF', 'GIF'), ('DOCUMENT', 'DOCUMENT'), ('LOCATION', 'LOCATION')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='templatecomponent',
            name='type',
            field=models.CharField(choices=[('HEADER', 'HEADER'), ('BODY', 'BODY'), ('FOOTER', 'FOOTER'), ('BUTTONS', 'BUTTONS')], max_length=128),
        ),
        migrations.AlterField(
            model_name='templatecomponentbutton',
            name='type',
            field=models.CharField(choices=[('QUICK_REPLY', 'QUICK_REPLY'), ('URL', 'URL'), ('PHONE_NUMBER', 'PHONE_NUMBER'), ('VOICE_CALL', 'VOICE_CALL'), ('COPY_CODE', 'COPY_CODE'), ('MPM', 'MPM'), ('SPM', 'SPM'), ('OTP', 'OTP')], max_length=128),
        ),
    ]
