# Generated by Django 6.0.2 on 2026-03-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0014_template_upd'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='fallback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
