# Generated by Django 6.0.2 on 2026-03-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_site_options_alter_site_domain'),
        ('waba', '0015_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='site',
        ),
        migrations.AddField(
            model_name='app',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='waba_apps', to='sites.site'),
        ),
    ]
