# Generated by Django 6.0.2 on 2026-03-07 05:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0016_remove_app_site_app_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='name',
            field=models.CharField(default='separator.biz', max_length=255),
        ),
        migrations.AddField(
            model_name='waba',
            name='dataset',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Ctwa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clid', models.CharField(max_length=2048)),
                ('waba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctwas', to='waba.waba')),
            ],
        ),
    ]
