# Generated by Django 6.0.2 on 2026-03-08 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0017_ctwa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtwaEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('event', models.CharField(max_length=128)),
                ('ctwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='waba.ctwa')),
            ],
        ),
    ]
