# Generated by Django 6.0.2 on 2026-03-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0018_ctwaevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctwa',
            name='source_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ctwa',
            name='source_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ctwa',
            name='source_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
