# Generated by Django 6.0.2 on 2026-03-23 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0019_ctwa_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctwa',
            name='phone',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ctwa',
            name='waba_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctwas', to='waba.phone'),
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='waba.phone')),
            ],
        ),
    ]
