# Generated by Django 6.0.2 on 2026-03-28 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0020_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('delete', 'delete')], max_length=16)),
                ('endpoint', models.CharField(blank=True, max_length=1024, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waba.phone')),
                ('waba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waba.waba')),
            ],
        ),
    ]
