# Generated by Django 6.0.2 on 2026-04-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0021_apicall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctwa',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
