# Generated by Django 6.0.3 on 2026-04-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0022_alter_ctwa_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.CharField(default='MARKETING', max_length=64),
        ),
    ]
