# Generated by Django 6.0.3 on 2026-04-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0023_template_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='ChatFromSms',
            field=models.BooleanField(default=False),
        ),
    ]
