# Generated by Django 6.0.3 on 2026-05-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0024_phone_chatfromsms'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='availableInB24',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='availabletoB24admins',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='voximplant_reg_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
