# Generated by Django 6.0.3 on 2026-05-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0025_upd_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='hosted',
            field=models.BooleanField(default=False, help_text='Enable Hosted Embedded Signup flow'),
        ),
        migrations.AddField(
            model_name='app',
            name='register',
            field=models.BooleanField(default=True, help_text='Register phone numbers after onboarding'),
        ),
        migrations.AddField(
            model_name='app',
            name='subscribe',
            field=models.BooleanField(default=True, help_text='Subscribe WABAs to webhook events'),
        ),
    ]
