# Generated by Django 6.0.5 on 2026-05-17 12:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0026_hosted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='business_app_onboarding',
            field=models.BooleanField(default=False, help_text='Enable WhatsApp Business App onboarding/coexistence Embedded Signup flow'),
        ),
        migrations.AddField(
            model_name='app',
            name='es_version',
            field=models.CharField(default='v4', max_length=10, verbose_name='ES Version'),
        ),
        migrations.AddField(
            model_name='app',
            name='session_info_version',
            field=models.CharField(default='3', max_length=10, verbose_name='Session Info Version'),
        ),
        migrations.CreateModel(
            name='PartnerApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('webhook_url', models.URLField()),
                ('redirect_url', models.URLField()),
                ('verify_token', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_apps', to='waba.app')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waba_partner_apps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='waba',
            name='partner_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wabas', to='waba.partnerapp'),
        ),
    ]
