# Generated by Django 6.0.5 on 2026-05-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0027_partners_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='app_instance',
        ),
        migrations.AddField(
            model_name='app',
            name='showObaForm',
            field=models.BooleanField(default=False, help_text='Show Official Business Account application form'),
        ),
    ]
