# Generated by Django 6.0.5 on 2026-05-30 10:00

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0028_upd'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='openai_api_key',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phone',
            name='transcribe_model',
            field=models.CharField(choices=[('gpt-4o-mini-transcribe', 'gpt-4o-mini-transcribe'), ('gpt-4o-transcribe', 'gpt-4o-transcribe'), ('gpt-4o-transcribe-diarize', 'gpt-4o-transcribe-diarize')], default='gpt-4o-mini-transcribe', max_length=50),
        ),
    ]
