# Generated by Django 6.0.5 on 2026-05-31 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0042_feature_upd'),
        ('waba', '0030_interactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waba_interactives', to='bitrix.bitrix'),
        ),
        migrations.AlterField(
            model_name='interactive',
            name='type',
            field=models.CharField(choices=[('button', 'Reply buttons'), ('list', 'List'), ('cta_url', 'CTA URL'), ('voice_call', 'Call button'), ('call_permission_request', 'Call permission request')], max_length=32),
        ),
    ]
