# Generated by Django 6.0.5 on 2026-05-31 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0031_interactive_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='error',
        ),
    ]
