# Generated by Django 6.0.5 on 2026-06-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0032_remove_phone_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='file_proxy',
            field=models.BooleanField(default=True, help_text='Proxy inbound files to Bitrix instead of saving temp files'),
        ),
    ]
