# Generated by Django 6.0.5 on 2026-06-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0033_fileproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive',
            name='global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interactive',
            name='hashtag',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='phone',
            name='read_receipts',
            field=models.BooleanField(default=False),
        ),
    ]
