# Generated by Django 6.0.5 on 2026-06-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0034_waba_upd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='hosted',
        ),
        migrations.AddField(
            model_name='app',
            name='auth_flow',
            field=models.CharField(choices=[('popup', 'Popup'), ('manual', 'Manual'), ('hosted', 'Hosted')], default='popup', max_length=20),
        ),
    ]
