# Generated by Django 6.0.6 on 2026-06-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0035_AuthFlow'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='retry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='error',
            name='subcode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
