# Generated by Django 6.0.6 on 2026-06-23 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0036_retry_upd'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='fallback_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_apps', to='waba.app'),
        ),
    ]
