# Generated by Django 6.0.8 on 2026-10-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waba', '0037_app_fallback_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='additional_codecs',
            field=models.BooleanField(default=False, help_text='Enable PCMA, PCMU'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='sip_hostname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
