# Generated by Django 5.2.5 on 2025-09-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0002_olxuser_attempts_olxuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olxuser',
            name='access_token',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='olxuser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
